import { useEffect,useMemo,useState } from "react";
import { KeyRound,Plus,Search,ShieldCheck,UserCheck,UserRoundCog,UsersRound } from "lucide-react";
import { api } from "../../services/api";

const roles=["SUPER_ADMIN","INSTITUTE_ADMIN","TEACHER","ACCOUNTANT","STAFF","PARENT","STUDENT"];
const empty={institutionId:"",name:"",username:"",email:"",password:"",role:"INSTITUTE_ADMIN",isActive:true};
const pretty=x=>x?.replaceAll("_"," ");

export function UsersPermissionsPage(){
 const [summary,setSummary]=useState({}); const [data,setData]=useState({items:[],page:1,totalPages:1,total:0,institutions:[]});
 const [filters,setFilters]=useState({search:"",role:"",institutionId:"",active:"",page:1,limit:10});
 const [form,setForm]=useState(empty); const [open,setOpen]=useState(false); const [edit,setEdit]=useState(null);
 const [resetUser,setResetUser]=useState(null); const [password,setPassword]=useState("");
 const [matrix,setMatrix]=useState({permissions:[],matrix:{},roles}); const [matrixOpen,setMatrixOpen]=useState(false); const [selectedRole,setSelectedRole]=useState("INSTITUTE_ADMIN");
 const [message,setMessage]=useState(""); const [error,setError]=useState("");
 async function load(){try{const [a,b,c]=await Promise.all([api.get("/platform/access/summary"),api.get("/platform/access/users",{params:filters}),api.get("/platform/access/permissions")]);setSummary(a.data.data);setData(b.data.data);setMatrix(c.data.data);setError("");}catch(e){setError(e.response?.data?.message||"Unable to load access management.");}}
 useEffect(()=>{const t=setTimeout(load,180);return()=>clearTimeout(t)},[filters.search,filters.role,filters.institutionId,filters.active,filters.page,filters.limit]);
 const grouped=useMemo(()=>matrix.permissions.reduce((a,p)=>{(a[p.module]??=[]).push(p);return a},{}),[matrix.permissions]);
 function newUser(){setEdit(null);setForm(empty);setOpen(true)}
 function editUser(u){setEdit(u);setForm({institutionId:u.institutionId||"",name:u.name,username:u.username,email:u.email||"",password:"",role:u.role,isActive:u.isActive});setOpen(true)}
 async function save(e){e.preventDefault();try{if(edit)await api.put(`/platform/access/users/${edit.id}`,form);else await api.post("/platform/access/users",form);setOpen(false);setMessage(edit?"User updated.":"User created.");load();}catch(err){setError(err.response?.data?.message||"Unable to save user.");}}
 async function toggle(u){try{await api.patch(`/platform/access/users/${u.id}/status`,{isActive:!u.isActive});setMessage(`${u.name} ${u.isActive?"disabled":"activated"}.`);load();}catch(e){setError(e.response?.data?.message||"Unable to update account.");}}
 async function reset(e){e.preventDefault();try{await api.post(`/platform/access/users/${resetUser.id}/reset-password`,{password});setResetUser(null);setPassword("");setMessage("Password reset successfully.");}catch(err){setError(err.response?.data?.message||"Unable to reset password.");}}
 function roleHas(id){return (matrix.matrix[selectedRole]||[]).includes(id)}
 function togglePermission(id){setMatrix(x=>{const current=x.matrix[selectedRole]||[];return {...x,matrix:{...x.matrix,[selectedRole]:current.includes(id)?current.filter(v=>v!==id):[...current,id]}}})}
 async function saveRole(){try{await api.put(`/platform/access/roles/${selectedRole}`,{permissionIds:matrix.matrix[selectedRole]||[]});setMessage(`${pretty(selectedRole)} permissions updated.`);setMatrixOpen(false);load();}catch(e){setError(e.response?.data?.message||"Unable to update role permissions.");}}
 return <>
  <div className="page-head"><div><h1>Users & Permissions</h1><p>Platform accounts, institution users, role permissions and security controls.</p></div><div className="access-head-actions"><button onClick={()=>setMatrixOpen(true)}><ShieldCheck size={16}/> Permission Matrix</button><button className="primary" onClick={newUser}><Plus size={16}/> Add User</button></div></div>
  {message&&<div className="success-message">{message}</div>}{error&&<div className="error">{error}</div>}
  <div className="access-stats"><article><UsersRound/><span>Total Users</span><strong>{summary.total||0}</strong></article><article><UserCheck/><span>Active</span><strong>{summary.active||0}</strong></article><article><UserRoundCog/><span>Institute Admins</span><strong>{summary.instituteAdmins||0}</strong></article><article><ShieldCheck/><span>Super Admins</span><strong>{summary.superAdmins||0}</strong></article><article><UsersRound/><span>Tenant Users</span><strong>{summary.tenantUsers||0}</strong></article><article><KeyRound/><span>Permissions</span><strong>{summary.permissions||0}</strong></article></div>
  <div className="filters institutions-filters"><div className="filter-search"><Search size={17}/><input placeholder="Search name, username, email or institution" value={filters.search} onChange={e=>setFilters(x=>({...x,search:e.target.value,page:1}))}/></div><select value={filters.institutionId} onChange={e=>setFilters(x=>({...x,institutionId:e.target.value,page:1}))}><option value="">All institutions</option>{data.institutions.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select><select value={filters.role} onChange={e=>setFilters(x=>({...x,role:e.target.value,page:1}))}><option value="">All roles</option>{roles.map(r=><option key={r}>{r}</option>)}</select><select value={filters.active} onChange={e=>setFilters(x=>({...x,active:e.target.value,page:1}))}><option value="">All statuses</option><option value="true">Active</option><option value="false">Disabled</option></select></div>
  <div className="panel table-wrap"><table><thead><tr><th>User</th><th>Institution</th><th>Role</th><th>Overrides</th><th>Last Login</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.items.map(u=><tr key={u.id}><td><b>{u.name}</b><small>@{u.username} · {u.email||"No email"}</small></td><td>{u.institution?.name||"Platform"}<small>{u.institution?.code||"Global account"}</small></td><td><span className="role-chip">{pretty(u.role)}</span></td><td>{u.permissionOverrides.length}<small>custom permission(s)</small></td><td>{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():"Never"}</td><td><span className={`badge ${u.isActive?"active":"suspended"}`}>{u.isActive?"ACTIVE":"DISABLED"}</span></td><td><div className="row-actions"><button onClick={()=>editUser(u)}>Edit</button><button onClick={()=>{setResetUser(u);setPassword("")}}>Reset Password</button><button className={u.isActive?"danger-action":""} onClick={()=>toggle(u)}>{u.isActive?"Disable":"Activate"}</button></div></td></tr>)}{!data.items.length&&<tr><td colSpan="7" className="empty-cell">No users found.</td></tr>}</tbody></table><div className="pagination"><button disabled={data.page<=1} onClick={()=>setFilters(x=>({...x,page:x.page-1}))}>Previous</button><span>Page {data.page} of {data.totalPages} · {data.total} users</span><button disabled={data.page>=data.totalPages} onClick={()=>setFilters(x=>({...x,page:x.page+1}))}>Next</button></div></div>
  {open&&<div className="modal-bg"><div className="modal"><div className="modal-head"><div><h2>{edit?"Edit User":"Create User"}</h2><p>Assign the correct role and tenant scope.</p></div><button onClick={()=>setOpen(false)}>×</button></div><form className="form-grid" onSubmit={save}><label>Name<input required value={form.name} onChange={e=>setForm(x=>({...x,name:e.target.value}))}/></label><label>Username<input required disabled={Boolean(edit)} value={form.username} onChange={e=>setForm(x=>({...x,username:e.target.value}))}/></label><label>Email<input type="email" value={form.email} onChange={e=>setForm(x=>({...x,email:e.target.value}))}/></label>{!edit&&<label>Password<input type="password" minLength="8" required value={form.password} onChange={e=>setForm(x=>({...x,password:e.target.value}))}/></label>}<label>Role<select value={form.role} onChange={e=>setForm(x=>({...x,role:e.target.value,institutionId:e.target.value==="SUPER_ADMIN"?"":x.institutionId}))}>{roles.map(r=><option key={r}>{r}</option>)}</select></label>{form.role!=="SUPER_ADMIN"&&<label>Institution<select required value={form.institutionId} onChange={e=>setForm(x=>({...x,institutionId:e.target.value}))}><option value="">Select institution</option>{data.institutions.map(i=><option value={i.id} key={i.id}>{i.name} ({i.code})</option>)}</select></label>}<div className="modal-actions"><button type="button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary">{edit?"Update User":"Create User"}</button></div></form></div></div>}
  {resetUser&&<div className="modal-bg"><div className="modal password-reset-modal"><div className="modal-head"><div><h2>Reset Password</h2><p>{resetUser.name} · @{resetUser.username}</p></div><button onClick={()=>setResetUser(null)}>×</button></div><form onSubmit={reset} className="reset-form"><label>New Password<input autoFocus type="password" required minLength="8" value={password} onChange={e=>setPassword(e.target.value)}/></label><div className="modal-actions"><button type="button" onClick={()=>setResetUser(null)}>Cancel</button><button className="primary">Reset Password</button></div></form></div></div>}
  {matrixOpen&&<div className="modal-bg"><div className="modal permission-modal"><div className="modal-head"><div><h2>Role Permission Matrix</h2><p>Configure default module and action access for each role.</p></div><button onClick={()=>setMatrixOpen(false)}>×</button></div><div className="permission-role-tabs">{roles.map(r=><button className={selectedRole===r?"active":""} onClick={()=>setSelectedRole(r)} key={r}>{pretty(r)}</button>)}</div>{selectedRole==="SUPER_ADMIN"&&<div className="permission-note">Super Admin always has full platform access.</div>}<div className="permission-groups">{Object.entries(grouped).map(([module,items])=><section key={module}><h3>{module}</h3>{items.map(p=><label key={p.id}><input type="checkbox" disabled={selectedRole==="SUPER_ADMIN"} checked={selectedRole==="SUPER_ADMIN"||roleHas(p.id)} onChange={()=>togglePermission(p.id)}/><span><b>{p.name}</b><small>{p.code}</small></span></label>)}</section>)}</div><div className="modal-actions"><button onClick={()=>setMatrixOpen(false)}>Cancel</button><button disabled={selectedRole==="SUPER_ADMIN"} className="primary" onClick={saveRole}>Save Permissions</button></div></div></div>}
 </>
}
